server:
  port: 18888
spring:
  application:
    name: springcloudalibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.120.80:8040
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: springcloudalibaba-order
          uri: lb://springcloudalibaba-order
          predicates:
            - Path=/order/**
        - id: springcloudalibaba-order
          uri: lb://springcloudalibaba-user
          predicates:
            - Path=/user/**
