server:
  port: 10001
spring:
  application:
    name: springcloudalibaba-user
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.120.80:8848
        username: 123
        password: 123
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
