server:
  port: 10011
spring:
  application:
    name: springcloudalibaba-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: x123
        password: x123
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always